### ISSUE TITLE
Linter not respecting the .sass-lint.yml rules

### ISSUE THREAD

**Issue by fernandofleury** [sasstools/gulp-sass-lint#16]
I was using `gulp-scss-lint` but I was trying to migrate to `sass-lint`. Migrated my whole `scss-lint.yml` to `sass-lint.yml`, but sass-lint does not respect my rules:

![image](https://cloud.githubusercontent.com/assets/2780941/10257758/a2361f88-692f-11e5-81df-7cb762efad5f.png)

For example, in my `.sass-lint.yml`:

``` yml
  # Avoid nesting selectors too deeply.
  nesting-depth:
    - 1
    -
      max-depth: 4
```

Both `gulpfile.js` and `.sass-lint.yml` files are on the root of the project. And I think the file is going to the plugin, because whenever i insert a typo on it, the plugin throws an error.

Honestly, I don't know what I'm missing here, I might be doing something wrong.
