### ISSUE TITLE
Files settings is ignored from .sass-lint.yml

### ISSUE THREAD

**Issue by cstuncsik** [sasstools/gulp-sass-lint#46]
Hi there,

``` yml
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
```

This section should extend the glob settings passed to the plugin.

I am in a situation that I have to lint just specific files (new ones) in a project but compile every files (old ones).
I have a config for my gulp tasks and the compile and the lint task is using the same glob settings but it would be better to control the linter file settings from yml config rather than introducing a new glob settings in my config just for linting.
