### ISSUE TITLE
Enable ability to disable linting rules via inline comment

### ISSUE THREAD

**Issue by barrymcgee** [sasstools/gulp-sass-lint#74]
According to the sass-lint docs, it should be possible to apply an ignore rule to certain lines - see: https://github.com/sasstools/sass-lint#disabling-linters-via-source

Can this also be made possible using `gulp-sass-lint` please?

**Comment by DanPurdy** [comment]
Gulp-sass-lint is already pointed at the newest version. If it's not working you'll need to delete your node modules and reinstall

**Comment by barrymcgee** [comment]
@DanPurdy Thank you for your quick reply and your work on this package.

I've just realised that the ignore rules do work if applied at a block level, but not inline level.

Example: These block ignore rules work...

```css
// sass-lint:disable border-zero
p {
  border: none; // No lint reported
}
// sass-lint:enable border-zero
```

...but inline ignore rules do not...

```css
// Lint reported
p {
  border: none; // sass-lint:disable-line border-zero
}
```
