### ISSUE TITLE
$important: !important; causes a fatal crash

### ISSUE THREAD

**Issue by Dan503** [sasstools/gulp-sass-lint#78]
If you write this in an scss file and try to lint it, it will cause a fatal crash:

````scss
$important: !important;
````

The error message for the crash is:

````
Cannot read property 'is' of undefined
````

If you are wondering why anyone would ever write that, it was inside a mixin and the `!important` was able to be toggled on or off:

````scss
@if ($isImportant) {
    $important: !important;
} @else {
    $important: unquote('');
}
````

I ended up managing to avoid the fatal crash by doing this:

````scss
@if ($isImportant) {
    $important: unquote('!important');
} @else {
    $important: unquote('');
}
````
